### ISSUE TITLE
Safety>Set spending pin = crash

### ISSUE THREAD

**Issue by TheButterZone** [LIMXTEC/bitcore-wallet#1]
When I set the spending PIN with an 8-character one, the app crashes every time - "Unfortunately, Bitcore Wallet has stopped."

https://github.com/LIMXTEC/BitCore/releases/download/0.14.1.6/Android-0-14-1-6.apk

**Comment by limxdev** [comment]
It is a new android version online.

**Comment by madzebra** [comment]
I've tried to reproduce this but haven't got any crash.

Can you give me a little more info?
How many transactions do you have (approximately, if you don't want to tell exact number)?
What is the Android version you're running the wallet?
How many free space do you have on your device?
Have you tried this on another device (if you have any)?

**Comment by TheButterZone** [comment]
0 TX, not going to TX with it until I set a spending PIN.
Android 4.4.2 
654 MB available (app data is 764 kb with 40 kb cache) - like the original Schildbach wallet, I have it set to only connect to trusted peer of 127.0.0.1, which if it was a problem, should crash the wallet at a time other than setting the spending PIN
Don't have another device

https://github.com/LIMXTEC/BitCore/releases/download/0.14.1.6/Android-0-14-1-6-3.apk crashes at the same moment.

**Comment by madzebra** [comment]
Can you use Options > Report issue and send your wallet dump? Thanks.

**Comment by TheButterZone** [comment]
Sent.

**Comment by madzebra** [comment]
8077e77ca90610493fa81e3fdd6591dbbf5f4c96c721e96ba4ae763f5867d46a

**Comment by madzebra** [comment]
Try new apk (link is the same). Sha256 sum is above.

The app crashes on your device with the error "out of memory". The reason of it is that your system allocates small amount of memory for apps. I hope new version will help with your issue.

**Comment by TheButterZone** [comment]
https://github.com/LIMXTEC/BitCore/releases/download/0.14.1.6/Android-0-14-1-6-3.apk = Page not found

**Comment by madzebra** [comment]
You can find the working link to the apk file on this page: https://github.com/LIMXTEC/BitCore/releases

**Comment by Amin2110** [comment]
Pay
